<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-D9BEU1J" failures="1" tests="1" name="Tests" time="5.962" errors="0" timestamp="2022-02-09T15:51:44 EET">
  <testcase classname="Tests.UMM1" name="UMM1PS1" time="3.279">
    <failure type="java.lang.AssertionError" message="expected [This user already exist.] but found [Sign up successful.]">
      <![CDATA[java.lang.AssertionError: expected [This user already exist.] but found [Sign up successful.]
at Tests.UMM1.UMM1PS1(UMM1.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UMM1PS1 -->
  <testcase classname="Tests.UMM1" name="UMM1AS3" time="0.0">
    <ignored/>
  </testcase> <!-- UMM1AS3 -->
  <testcase classname="Tests.UMM1" name="UMM1AS1" time="0.0">
    <ignored/>
  </testcase> <!-- UMM1AS1 -->
  <testcase classname="Tests.UMM1" name="UMM1AS2" time="0.0">
    <ignored/>
  </testcase> <!-- UMM1AS2 -->
</testsuite> <!-- Tests -->
